services:
  frontend-angular:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend-dotnet
    environment:
      - API_URL=http://backend-dotnet:5000
    networks:
      - app-network

  backend-dotnet:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - ml-service-python
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ML_SERVICE_URL=http://ml-service-python:8000
      - ConnectionStrings__DefaultConnection=Data Source=app.db
    networks:
      - app-network

  ml-service-python:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
